fix unit-tests for numpy 1.20
stack-of-tasks/eigenpy pull request #223
Opened 2021-03-05 19:51 UTC by nim65s

Hi,

The `py-user-type` stopped working on Arch with numpy 1.20 (which requires python >= 3.7).

I didn't see anything related to safe casts or  `num_type` changes in the [changelog](https://github.com/numpy/numpy/releases/tag/v1.20.0), but switching from `numpy<1.20` to `numpy >=1.20` easily shows that the tests were working in 1.19.5 and are failing since 1.20.0.

This PR tries to address that. 
The first commit seems legit to me, but the second feels more like a hack. 
I think we shouldn't get that `dtype('O')` in the first place. I checked that `dotfunc` was called in 1.19.5, but isn't called anymore on 1.20.0, so maybe the issue is more at the registration step.

2021-03-06 06:32 UTC, jcarpent requested changes
I totally don’t understand the change you made. At the same time, don’t change the API.

2021-03-23 08:19 UTC, jcarpent commented
@nim65s Any feedback on this fix?

2021-03-23 09:16 UTC, nim65s commented
I need to make a better version of this, but this require investigation time to understand why numpy 1.20 started to return `NPY_OBJECT` instead of the expected user defined type.

2021-04-16 17:11 UTC, jcarpent commented
Duplicate with #228.

2021-04-16 17:11 UTC, closed without merging