Add support of std::pair
stack-of-tasks/eigenpy pull request #417
Opened 2023-12-11 17:15 UTC by jcarpent

2023-12-11 17:15 UTC, hrp2-14 commented
Hi ! This project doesn't usually accept pull requests on the main branch.
If this wasn't intentionnal, you can change the base branch of this PR to devel
(No need to close it for that). Best, a bot.

2023-12-12 10:42 UTC, jorisv requested changes

2023-12-12 10:42 UTC, jorisv commented on unittest/python/test_std_pair.py
> +assert std_pair_to_tuple(t) == t
Add a cpp => python conversion

2023-12-12 10:42 UTC, jorisv commented on include/eigenpy/std-pair.hpp
> +        reinterpret_cast<void* (*)(_object*)>(&convertible), &construct,
```suggestion
        &convertible, &construct,
```
The reinterpret_cast seem to be useless.

2023-12-12 10:42 UTC, jorisv commented on unittest/CMakeLists.txt
> +                     "python;unittest")
```suggestion
                     "unittest")
```
Since we don't import eigenpy, we don't need python module in PYTHONPATH.

2023-12-12 11:09 UTC, jorisv approved these changes

2023-12-12 12:08 UTC, merged